name: Development
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: .env
          envkey_NODE_ENV: development
          envkey_PORT: 3000
          envkey_DB_HOST: ${{secrets.DEV_DB_HOST}}
          envkey_DB_USER: ${{secrets.DEV_DB_USER}}
          envkey_DB_PASSWORD: ${{secrets.DEV_DB_PASSWORD}}
          envkey_DB_NAME: ${{secrets.DEV_DB_NAME}}
          envkey_DB_PORT: 3306
          envkey_DB_LOGGING: true
          envkey_MAPBOX_TOKEN: ${{secrets.DEV_MAPBOX_TOKEN}}
          envkey_GOOGLE_MAPS_KEY: ${{secrets.DEV_GOOGLE_MAPS_KEY}}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          REMOTE_HOST: ${{ secrets.DEV_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEV_REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SERVER_SSH_KEY }}
          TARGET: 'distrologiq-dev'
          ARGS: '-rltgoDzvO --delete'
          SOURCE: '.'
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: |
            cd distrologiq-dev
            pm2 delete distrologiq-dev
            pm2 start --name distrologiq-dev npm -- run start:prod
